# Generated by Django 5.1.6 on 2025-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('total_steps', models.IntegerField()),
                ('total_distance', models.FloatField()),
                ('very_active_distance', models.FloatField()),
                ('moderately_active_distance', models.FloatField()),
                ('light_active_distance', models.FloatField()),
                ('sedentary_active_distance', models.FloatField()),
                ('very_active_minutes', models.IntegerField()),
                ('fairly_active_minutes', models.IntegerField()),
                ('lightly_active_minutes', models.IntegerField()),
                ('sedentary_minutes', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
